name: Build notebook-kit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      #- run: npm install
      - run: npm ci
      - run: node build.js

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f dist
          git add package-lock.json
          git commit -m "Update dist build" || exit 0
          git push
